export { ArchitectureDiagram } from "./ArchitectureDiagram"
export { ArchitectureNotes }   from "./ArchitectureNotes"
export { ArchitecturePage }    from "./ArchitecturePage"
export { DiagramViewer }       from "./DiagramViewer"
export { NodeContent }         from "./NodeContent"
export { NodeDetailPanel }     from "./NodeDetailPanel"
export { NODES, getNodeBySlug } from "./nodes"
export type { NodeId, AppRouterNodeId, TileProviderNodeId, ArchNodeConfig } from "./nodes"
export type { ArchNode }       from "./types"
// ArchitectureViewer removed — deleted
